### PR TITLE
Polish things up

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
I looked at the upstream library and I didn't see a keyword arg named `input` or `input_` (or `output` either).

The renaming of `input` to `input_` seems kind of confusing, and I see it as something that will need to be explained. Could you pick a different set of names that are consistent, `prompt_input`, or `command_input`, or something like that?

**Comment by tannewt** [comment]
> I looked at the upstream library and I didn't see a keyword arg named `input` or `input_` (or `output` either).

It is here: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/5b3dd6dbbd72ac8323e749cc12e6aa2d7c7411af/src/prompt_toolkit/shortcuts/prompt.py#L409

**Comment by dhalbert** [comment]
@tannewt aaaahhh -- too bad they did that. :)

**Review by dhalbert — APPROVED** [review]
Did not test, changes look fine.

**Pull request merged**
